// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateMarket.Api.Context;

#nullable disable

namespace RealEstateMarket.Api.Migrations
{
    [DbContext(typeof(RealEstateMarketContext))]
    partial class RealEstateMarketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstateMarket.Api.Models.RealEstate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HouseNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("ZipCode")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Real estate");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb4a0985-6f04-48e9-aed9-a186479ff088"),
                            City = "Budapest",
                            Description = "leírás",
                            Email = "lorem@ipsum.net",
                            HouseNumber = 10L,
                            Phone = "+36301234567",
                            Price = 50000000L,
                            Region = "Pest",
                            StreetName = "Petőfi Sándor utca",
                            ZipCode = (short)1234
                        },
                        new
                        {
                            Id = new Guid("5e256c66-e291-4f2d-8b90-c5f5f3f8e773"),
                            City = "Budapest",
                            HouseNumber = 10L,
                            Phone = "+36302345678",
                            Price = 380000000L,
                            Region = "Pest",
                            StreetName = "Kossuth Lajos utca",
                            ZipCode = (short)1234
                        },
                        new
                        {
                            Id = new Guid("b3666060-38bb-4000-9963-d4c37727980d"),
                            City = "Zalaegerszeg",
                            Description = "leírás2",
                            HouseNumber = 335L,
                            Price = 29000000L,
                            Region = "Zala",
                            StreetName = "Arany János út",
                            ZipCode = (short)8900
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
